### ISSUE TITLE
Bug - Safari does not support input[type=color]

### ISSUE THREAD

**Issue by jastkand** [maxwellito/triangulart#10]
Safari of 9.1 and older versions does not support inputs of color type – http://caniuse.com/#feat=input-color. So the color input looks this way
![](https://monosnap.com/file/31kvHfvVAdmi0KZSNpwmG4GAf8CGQJ.png)

**Comment by maxwellito** [comment]
Arrrgg damn Safari. Well, I guess I have to use a polyfill for these sweet browsers. I put it on my list. Thanks for the issue :)

**Comment by maxwellito** [comment]
Its now fixed ;)
