### ISSUE TITLE
'fork me on github' link

### ISSUE THREAD

**Issue by dirkk0** [maxwellito/triangulart#13]
Hi,

  very cool!

I came here via http://us5.campaign-archive2.com/?u=ea228d7061e8bbfa8639666ad&id=d3da9804df&e=5d8607bb11

Maybe you could include a link to this repository on
http://maxwellito.github.io/triangulart/
?

Thanks,
 Dirk

**Comment by maxwellito** [comment]
Hi Dirk,
Thanks for the suggestion. This repo was very silent for a while, and I realised that I wasn't watching the repo, so I got no notifications from all interactions.
The v2 is out, in beta, and from the home screen there a little link to the repo.
See ya
