### ISSUE TITLE
Bug - "White" color swatch is invisible

### ISSUE THREAD

**Issue by flukeout** [maxwellito/triangulart#5]
Because the color swatches don't have a border, white is currently invisible...

Editor with white color added, but not selected...

![image](https://cloud.githubusercontent.com/assets/25212/14218585/ffed63f2-f809-11e5-8412-1fc2f244e2b2.png)

Selected...

![image](https://cloud.githubusercontent.com/assets/25212/14218599/1ba4798c-f80a-11e5-883c-2fe2aacfdc2f.png)

How about a faint border on the swatches so you can see very faint colors?

**Comment by maxwellito** [comment]
Fixed with https://github.com/maxwellito/triangulart/pull/1
