### ISSUE TITLE
UX Improvement - Don't stop coloring if I mouse off of the triangles and come back.

### ISSUE THREAD

**Issue by flukeout** [maxwellito/triangulart#7]
If I'm coloring and accidentally mouse off of the canvas area and then come back it won't keep coloring (even if I haven't let go of the mouse button)

Like this...

![triangles](https://cloud.githubusercontent.com/assets/25212/14218791/47ca95c2-f80b-11e5-89ac-23f16825a029.gif)

**Comment by maxwellito** [comment]
Oh I understand the other PR now. I made this explicitly, but you make me realize it wasn't wise at all. Gotcha.
Thanks for the nice issue.
